Repository AY2425S2-CS2103T-T16-3/tp, pull requests merged in 2025-04, with the labels that each got.

#129 Generate docs using markbind
  .github/workflows/docs.yml
  .gitignore
  docs/.gitignore
  docs/AboutUs.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Gemfile
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_data/projects.yml
  docs/_includes/custom-head.html
  docs/_includes/head.html
  docs/_includes/header.html
  docs/_layouts/alt-page.html
  docs/_layouts/default.html
  docs/_layouts/page.html
  docs/_markbind/layouts/default.md
  docs/_markbind/variables.json
  docs/_markbind/variables.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-mixins.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
  docs/_sass/minima/initialize.scss
  docs/_sass/minima/skins/classic.scss
  docs/_sass/minima/skins/solarized-dark.scss
  docs/_sass/minima/skins/solarized.scss
  docs/assets/css/style.scss
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/LogicStorageDIP.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/index.md
  docs/package-lock.json
  docs/package.json
  docs/site.json
  docs/stylesheets/main.css
  docs/team/johndoe.md
Labels: priority.Medium, type.Task, type.Documentation

#170 Add theme-command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Theme.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ThemeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/commons/core/ThemeTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ThemeCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/ThemeCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.Medium, type.Story, type.UI

#157 Fix schedule commands bugs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ListScheduleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/schedule/AddScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/ScheduleBoard.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/main/java/seedu/address/storage/JsonSerializableScheduleBoard.java
  src/main/java/seedu/address/storage/ScheduleBoardStorage.java
  src/main/java/seedu/address/ui/ScheduleCard.java
  src/main/resources/css/schedule-card.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/ScheduleListCard.fxml
  src/main/resources/view/ScheduleListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/schedule/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/UniqueScheduleListTest.java
  src/test/java/seedu/address/storage/JsonSerializableScheduleBoardTest.java
  src/test/java/seedu/address/testutil/ScheduleUtil.java
Labels: priority.High, alpha-bug

#174 Update footer status bar to dispay scheduleboard.json path
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddJCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/AddScheduleCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: alpha-bug

#150 Add option to save schedules to file
  .gitignore
  docs/DeveloperGuide.md
  docs/diagrams/ManualStorageClassDiagram.puml
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SaveCommandParser.java
  src/main/java/seedu/address/storage/ManualStorage.java
  src/main/java/seedu/address/storage/ManualStorageManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SaveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SaveCommandParserTest.java
Labels: priority.Medium, type.Enhancement, severity.Medium, type.Bug, alpha-bug

#152 Implement light theme for HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkHelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/LightHelpWindow.css
Labels: priority.Medium, severity.VeryLow, type.UI, alpha-bug

#181 Document save feature
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: priority.High, type.Task, severity.Medium, type.Bug, type.Documentation, alpha-bug

#253 Update images
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: type.Task
