Repository AY2425S2-CS2103T-T16-3/tp, pull requests merged in 2025-03, with the labels that each got.

#19 Update AboutUs.md with HarishB99's details
  docs/AboutUs.md
  docs/team/harishb99.md
Labels: type.Task

#31 Add new ui mockup screenshot
  docs/images/Ui.png
Labels: type.Task

#37 Acknowledge the original source of the code in README.md
  README.md
Labels: type.Task

#38 Update the link of the GitHub Actions
  README.md
Labels: type.Task

#32 Update the target user profile and value proposition
  docs/DeveloperGuide.md
Labels: type.Task

#44 Updated Use Cases
  docs/DeveloperGuide.md
Labels: type.Task

#55 Update URL of UserGuide to teams UserGuide Website
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#80 Fix display of `schedule` and `remark`
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/css/person-card.css
  src/main/resources/view/PersonListCard.fxml
Labels: severity.VeryLow

#91 fix: Make optional parameters to be optional
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: severity.Medium, type.Bug

#123 Enable Java assertions in `build.gradle`
  build.gradle
Labels: priority.High, type.Task

#108 Add `save` command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SaveCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SaveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SaveCommandParserTest.java
Labels: priority.Medium, type.Story

#124 Update Ui.png and helpMessage.png
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: type.Task
